### ISSUE TITLE
rsync hyak directory with local directory

### ISSUE THREAD

**Issue by sr320** [RobertsLab/hyak_mox#1]
It would be great if there were a way to `rsync` hyak directory with local directory. 

Needs to be no more complex than a script executed when logged into hyak. Ideally from login node.

**Comment by kubu4** [comment]
Did you figure out a solution? I just came to the issues to ask exactly this! If yes, can you post solution?

**Comment by sr320** [comment]
so I do not use a script but when working in hyak I will have a ssh session with owl open and run...

```
rsync -avz sr320@mox.hyak.uw.edu:/gscratch/srlab/sr320/ /var/services/web/halfshell/bu-mox/
```

thus syncing my entire directory to owl.

**Comment by kubu4** [comment]
Out of curiosity, why are you SSHing into Owl vs. mounting?

**Comment by sr320** [comment]
To me it is just cleaner, more flexible habit. i.e. Can do without being
connected to Hyak (from different computer etc.)
